/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package demo.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
public class DemoPluginPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getPlugins().apply(JSassWebjarsPlugin.class)
    }
}
